- name: install catalogue
  become: yes
  hosts: catalogue
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name: Enable Node.js 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Node.js 20
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create system user 'roboshop'
      ansible.builtin.user:
        name: roboshop
        comment: "roboshop system user"
        system: yes
        home: /app
        shell: /sbin/nologin
        create_home: no
    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: download catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
        dest: /tmp/catalogue.zip

    - name: extract catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service to system directory
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: systemctl daemon reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: start and enable catalogue
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check products loaded or not
      ansible.builtin.command: mongosh --host mongodb.venaws.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print catalogue output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: load products
      ansible.builtin.shell: mongosh --host mongodb.venaws.site < /app/db/master-data.js
      when: catalogue_output.stdout | int < 0
