- name: install redis
  hosts: redis
  become: yes
  tasks:
    - name: dnf module disable redis -y
      ansible.builtin.command: dnf module disable redis -y
    - name: dnf module enable redis:7 -y
      ansible.builtin.command: dnf module enable redis:7 -y
    - name: dnf install redis
      ansible.builtin.dnf:
        name: redis
        state: present
      
    - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: disable protected mode
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode'
        line: protected-mode no
      
    - name: enable and start redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes